-- =====================================================================
-- TBL_BIZI_MST 택배 정보 반영 (2026-08-06, 원자료: D:코네트택배관련테스트 자료1.xlsx)
--   ① 택배 칼럼 신설 : PARCEL_ADDR(택배주소) · PARCEL_TEL · PARCEL_HP
--      → 화면·엑셀은 "PARCEL_ADDR 우선, 없으면 ADDR" 로 쓴다
--   ② 엑셀의 사업장별 주소·전화를 매칭된 20건에 채운다 (기존 값 있으면 덮지 않음)
-- =====================================================================
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('dbo.TBL_BIZI_MST') AND name='PARCEL_ADDR')
BEGIN
    ALTER TABLE dbo.TBL_BIZI_MST ADD PARCEL_ADDR NVARCHAR(400) NULL, PARCEL_TEL NVARCHAR(60) NULL, PARCEL_HP NVARCHAR(60) NULL;
END
GO
-- 호호솥밥 청주 청원점  →  호호솥밥(청주 청원점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'충북 청주시 청원구 내덕동 295-2 1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'0507-1413-0961'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'0507-1413-0961'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0393896';
GO
-- 호호솥밥북구본점  →  호호솥밥(북구본점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'광주광역시 북구 서양로41번길 31, 1층(중흥동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'0503-6229-8204'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'0503-6229-8204'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0407353';
GO
-- 호호솥밥[전남 나주점]  →  호호솥밥(전남 나주점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'전라남도 나주시 빛가람로 746, 1층 106호'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-6404-9874'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-6404-9874'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0373097';
GO
-- 호호솥밥 경기부천점  →  호호솥밥(경기 부천점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'경기도 부천시 원미구 장말로 216번길6 1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-9491-3241'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-9491-3241'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0394103';
GO
-- 꾸아[구월로데오점]  →  꾸아(구월로데오점)(신)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'인천광역시 남동구 예술로126, 2층 209호(구월동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-6511-6699'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-6511-6699'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0389733';
GO
-- 꾸아[강릉교동점]  →  꾸아(강릉교동점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'강원도 강릉시 하슬라로 149-1 ,1층(교동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-7262-6412'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-7262-6412'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0325961';
GO
-- 꾸아[이대점]  →  꾸아(이대점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'서울특별시 서대문구 이화여대길 42, 2층 점포 한 칸(대현동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-5133-3040'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-5133-3040'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0335791';
GO
-- 뜨돈 대구 진천 본점  →  뜨돈 대구 진천 본점
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'대구광역시 달서구 진천로9길 30'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-8586-3075'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-8586-3075'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0361325';
GO
-- 호호솥밥[전남목포점]  →  호호솥밥(전남 목포점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'전라남도 목포시 삼향천로 37 (옥암동)상가동 102호'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-8342-3870'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-8342-3870'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0355054';
GO
-- 호호솥밥(전북 익산점)  →  호호솥밥(전북 익산점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'전북특별자치도 익산시 익산대로54길68, 1층 102호(신동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-4055-8449'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-4055-8449'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0399368';
GO
-- 호호솥밥광주북구점  →  호호솥밥(광주 북구점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'광주 북구 저불로31번길 14-3'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-4092-2261'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-4092-2261'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0351955';
GO
-- 호호솥밥 대구달서점  →  호호솥밥(대구 달서점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'대구광역시 달서구 장기로 57서길19 1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-9890-6960'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-9890-6960'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0396772';
GO
-- 호호솥밥(고양 일산점)  →  호호솥밥(고양 일산점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'경기도 고양시 일산서구 일산로 528, 1층 호호솥밥 일산점'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-3227-3333'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-3227-3333'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0395444';
GO
-- 호호솥밥[부산 서면점]  →  호호솥밥(부산 서면점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'부산광역시 부산진구 성지로 20, 1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-4534-1956'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-4534-1956'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0375372';
GO
-- 오늘도사시미 선화점  →  오늘도사시미_선화점
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'대전광역시 중구 중앙로 23-12 제B동 1층(선화동)'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-4788-0677'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-4788-0677'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0349430';
GO
-- 꾸아[강남역삼성타운점]  →  꾸아(강남역삼성타운점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'서울특별시 서초구 서초대로74길 29 104호'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-5202-5734'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-5202-5734'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0356818';
GO
-- 호호솥밥 비전점  →  호호솥밥(평택 비전점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'경기 평택시 비전6길 34-2 1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'0507-1383-3884'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'0507-1383-3884'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0402426';
GO
-- 호호솥밥 서대문점  →  호호솥밥(서울 서대문점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'서울시 서대문구 모래내로 15길58 지하1층'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-8355-2037'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-8355-2037'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0401568';
GO
-- 호호솥밥 경기안산  →  호호솥밥(경기 안산점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'경기도 안산시 단원구 고잔1길17 지하1층 122'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-9408-0524'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-9408-0524'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0400332';
GO
-- 호호솥밥 경기안산  →  호호솥밥(경기 안산점)
UPDATE dbo.TBL_BIZI_MST SET PARCEL_ADDR = ISNULL(NULLIF(PARCEL_ADDR,''), N'경기도 안산시 단원구 고잔1길17 지하1층 122'), PARCEL_TEL = ISNULL(NULLIF(PARCEL_TEL,''), N'010-9408-0524'), PARCEL_HP = ISNULL(NULLIF(PARCEL_HP,''), N'010-9408-0524'), UPD_DTTM = GETDATE(), UPD_USER = N'parcel_import' WHERE BIZ_CD = 'A0403069';
GO
